version: "2"
services:
  sqlite3:
        image: sqlite:3
        contaniner_name: sqlite3
        volumes:
         - ./sqlite3:/application
         restart: always
         
         ports:
           - 8080:8080
           
   web:
       container_name: flask
       build:
         context: ./
         volumes:
            - ./:/var/www/html
          ports:
             - 8080:8080
          depends_on:
             - sqlite3
    
    
